jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin


credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: SYSTEM
              id: user1
              username: Administrator
              password: secretPassword
          - basicSSHUserPrivateKey:
              scope: SYSTEM
              id: agent-private-key
              username: agentuser
              passphrase: password
              description: "ssh private key used to connect ssh slaves"
              privateKeySource:
                directEntry:
                  privateKey: sp0ds9d+skkfjf
          - file:
              scope: GLOBAL
              id: "secret-file"
              fileName: "mysecretfile.txt"
              secretBytes: "YWJjZGVmZwo="


security:
  globaljobdslsecurityconfiguration:
    useScriptSecurity: false

unclassified:
  location:
    url: http://localhost:8083/
  globalLibraries:
    libraries:
      - name: "ortak-kutuphane"
        defaultVersion: "main"
        implicit: true
        retriever:
          modernSCM:
            scm:
              git:
                id: "ortak-kutuphane-pipeline-shared-lib"
                remote: "https://github.com/cemtopkaya/jenkins-paylasilan-kutuphane-ornegi.git"
                branches:
                  - name: "*/main"
  themeManager:
    disableUserThemes: true
    theme: "darkSystem" # use "dark" for forcing the dark theme regardless of OS settings

jobs:
  - script: >
      freeStyleJob("freeStyleJob > basit-freestyle-job") {
        steps {
            shell "echo freestyle içinden merhaba"
        }
      }
  - script: queue("basit-freestyle-job")
  - script: |
        freeStyleJob("projenin-adi").with {
            displayName("freeStyleJob > Job Listesinde Gorunen Adi")
            label("master")
            parameters {
                stringParam("SCM_REPO","https://github.com/cemtopkaya/jenkinsfile-node-script-ornegi.git", "git adresi")
                stringParam("SCM_BRANCH","main", "Git adresindeki hangi bransi cekecegimiz")
            }
            scm {
                git("${SCM_REPO}", "${SCM_BRANCH}")
                
                //@Library("ortak-kutuphane@main") _
                //def lib = library("ortak-kutuphane@main")
                //sayHello "Selam sana ey dunya"
            }
            steps {
            }
        }
  - script: >
      pipelineJob("pipelineJob > jenkinsfile-ornegi") {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url("https://github.com/cemtopkaya/jenkinsfile-node-script-ornegi.git")
                }
                branch("*/main")
              }
            }
            lightweight()
          }
        }
      }
  # - script: queue("basit-freestyle-job")